export const FETCH_MY_MESSAGES          = 'app/MY_DATA/FETCH_MY_MESSAGES';
export const FETCH_MY_MESSAGES_FAILED   = 'app/MY_DATA/FETCH_MY_MESSAGES_FAILED';
export const FETCH_MY_MESSAGES_INFLIGHT = 'app/MY_DATA/FETCH_MY_MESSAGES_INFLIGHT';
export const FETCH_MY_MESSAGES_SUCCESS  = 'app/MY_DATA/FETCH_MY_MESSAGES_SUCCESS';

export const DELETE_MESSAGE          = 'app/MY_DATA/DELETE_MESSAGE';
export const DELETE_MESSAGE_FAILED   = 'app/MY_DATA/DELETE_MESSAGE_FAILED';
export const DELETE_MESSAGE_INFLIGHT = 'app/MY_DATA/DELETE_MESSAGE_INFLIGHT';
export const DELETE_MESSAGE_SUCCESS  = 'app/MY_DATA/DELETE_MESSAGE_SUCCESS';
