export const FETCH_MY_MESSAGES          = 'app/MY_DATA/FETCH_MY_MESSAGES';
export const FETCH_MY_MESSAGES_FAILED   = 'app/MY_DATA/FETCH_MY_MESSAGES_FAILED';
export const FETCH_MY_MESSAGES_INFLIGHT = 'app/MY_DATA/FETCH_MY_MESSAGES_INFLIGHT';
export const FETCH_MY_MESSAGES_SUCCESS  = 'app/MY_DATA/FETCH_MY_MESSAGES_SUCCESS';
